/**
 * Mock data for testing the wardrobe UI
 * These are sample wardrobe items to display before real data is available
 */

import { WardrobeItem } from '@/types/wardrobe';

export const mockWardrobeItems: WardrobeItem[] = [
  {
    id: '1',
    userId: 'mock-user',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    isolatedImageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    category: 'Top',
    subcategory: 'T-Shirt',
    color: 'Blue',
    material: 'Cotton',
    attributes: ['casual', 'summer', 'comfortable'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: 'mock-user',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    isolatedImageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    category: 'Bottom',
    subcategory: 'Jeans',
    color: 'Dark Blue',
    material: 'Denim',
    attributes: ['casual', 'versatile', 'classic'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    userId: 'mock-user',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    isolatedImageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    category: 'Shoes',
    subcategory: 'Sneakers',
    color: 'White',
    material: 'Leather',
    attributes: ['sporty', 'comfortable', 'versatile'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    userId: 'mock-user',
    imageUrl: 'https://images.unsplash.com/photo-1594938291221-94d19b0f8c13?w=400',
    isolatedImageUrl: 'https://images.unsplash.com/photo-1594938291221-94d19b0f8c13?w=400',
    category: 'Top',
    subcategory: 'Dress Shirt',
    color: 'White',
    material: 'Cotton',
    attributes: ['formal', 'professional', 'classic'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    userId: 'mock-user',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
    isolatedImageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
    category: 'Outerwear',
    subcategory: 'Jacket',
    color: 'Black',
    material: 'Leather',
    attributes: ['edgy', 'warm', 'stylish'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    userId: 'mock-user',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    isolatedImageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    category: 'Accessories',
    subcategory: 'Watch',
    color: 'Silver',
    material: 'Metal',
    attributes: ['elegant', 'professional', 'timeless'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
